config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # deviseを使用するURLに「users」を含むという記述

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  resources :posts, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit update destroy], shallow: true
    collection do
      get :bookmarks
  end
end
resources :bookmarks, only: %i[create destroy]
resource :profile, only: %i[show edit update]


  # Defines the root path route ("/")
  root 'static_pages#top'
end

app/views/shared/_footer.html.erb
<footer class="footer footer-center bg-base-200 text-base-content rounded p-10">
  <nav class="grid grid-flow-col gap-4">
    <a class="link link-hover">利用規約</a>
    <a class="link link-hover">プライバシーポリシー</a>
    <a class="link link-hover">お問い合わせ</a>
  </nav>
  <nav>
    <div class="grid grid-flow-col gap-4">
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
        </svg>
      </a>

    </div>
  </nav>
  <aside>
    <p> © 2024 - 美は一日にしてならず</p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to safe_join(['美は一日に', tag.br, 'してならず']), root_path, class: 'btn btn-ghost' %>
  </div>

  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <% unless user_signed_in? %>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <li><%= link_to "ユーザー登録", new_user_registration_path %></li>
      <% end %>

      <% if user_signed_in? %>
        <li>
          <details class="relative z-50">
            <summary>メニュー</summary>
            <ul class="bg-base-100 rounded-t-none p-2 absolute z-50 w-40">
              <li class="whitespace-nowrap overflow-hidden text-ellipsis truncate"><%= link_to "マイページ", profile_path %></li>
              <li class="whitespace-nowrap overflow-hidden text-ellipsis truncate"><%= link_to "投稿一覧", posts_path %></li>
              <li class="whitespace-nowrap overflow-hidden text-ellipsis truncate"><%= link_to "新規投稿", new_post_path %></li>
              <li class="whitespace-nowrap overflow-hidden text-ellipsis truncate"><%= link_to "これやる！リスト", bookmarks_posts_path %></li>
              <li class="whitespace-nowrap overflow-hidden text-ellipsis truncate">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
              </li>
            </ul>
          </details>
        </li>

        <!-- ユーザーアイコン -->
        <div>
          <%= link_to profile_path, class: "block w-12 h-12 rounded-full shadow-md hover:shadow-lg transition duration-300 transform hover:scale-105" do %>
            <%= image_tag "icon1.png", alt: "User Icon", class: "w-full h-full rounded-full object-cover" %>
          <% end %>
        </div>
      <% end %>
    </ul>
  </div>
</div>